/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as chatRouteRouteImport } from './routes/(chat)/route'
import { Route as chatIndexRouteImport } from './routes/(chat)/index'
import { Route as chatChatIndexRouteImport } from './routes/(chat)/chat/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as authAccountIndexRouteImport } from './routes/(auth)/account/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as chatChatIdIndexRouteImport } from './routes/(chat)/chat/$id/index'

const chatRouteRoute = chatRouteRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => rootRouteImport,
} as any)
const chatIndexRoute = chatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => chatRouteRoute,
} as any)
const chatChatIndexRoute = chatChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => chatRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAccountIndexRoute = authAccountIndexRouteImport.update({
  id: '/(auth)/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const chatChatIdIndexRoute = chatChatIdIndexRouteImport.update({
  id: '/chat/$id/',
  path: '/chat/$id/',
  getParentRoute: () => chatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account/': typeof authAccountIndexRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/chat/': typeof chatChatIndexRoute
  '/chat/$id/': typeof chatChatIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/account': typeof authAccountIndexRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/chat': typeof chatChatIndexRoute
  '/chat/$id': typeof chatChatIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(chat)': typeof chatRouteRouteWithChildren
  '/(chat)/': typeof chatIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/account/': typeof authAccountIndexRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(chat)/chat/': typeof chatChatIndexRoute
  '/(chat)/chat/$id/': typeof chatChatIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/account/'
    | '/sign-in/'
    | '/sign-up/'
    | '/chat/'
    | '/chat/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/account'
    | '/sign-in'
    | '/sign-up'
    | '/chat'
    | '/chat/$id'
  id:
    | '__root__'
    | '/(chat)'
    | '/(chat)/'
    | '/api/auth/$'
    | '/(auth)/account/'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(chat)/chat/'
    | '/(chat)/chat/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  chatRouteRoute: typeof chatRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  authAccountIndexRoute: typeof authAccountIndexRoute
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(chat)': {
      id: '/(chat)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof chatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/': {
      id: '/(chat)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof chatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/(chat)/chat/': {
      id: '/(chat)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof chatChatIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/account/': {
      id: '/(auth)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof authAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(chat)/chat/$id/': {
      id: '/(chat)/chat/$id/'
      path: '/chat/$id'
      fullPath: '/chat/$id/'
      preLoaderRoute: typeof chatChatIdIndexRouteImport
      parentRoute: typeof chatRouteRoute
    }
  }
}

interface chatRouteRouteChildren {
  chatIndexRoute: typeof chatIndexRoute
  chatChatIndexRoute: typeof chatChatIndexRoute
  chatChatIdIndexRoute: typeof chatChatIdIndexRoute
}

const chatRouteRouteChildren: chatRouteRouteChildren = {
  chatIndexRoute: chatIndexRoute,
  chatChatIndexRoute: chatChatIndexRoute,
  chatChatIdIndexRoute: chatChatIdIndexRoute,
}

const chatRouteRouteWithChildren = chatRouteRoute._addFileChildren(
  chatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  chatRouteRoute: chatRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  authAccountIndexRoute: authAccountIndexRoute,
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
