/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteRouteImport } from './routes/api/chat/route'
import { Route as appChatRouteRouteImport } from './routes/(app)/chat/route'
import { Route as appChatIndexRouteImport } from './routes/(app)/chat/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appauthSignUpIndexRouteImport } from './routes/(app)/(auth)/sign-up/index'
import { Route as appauthSignInIndexRouteImport } from './routes/(app)/(auth)/sign-in/index'
import { Route as appauthAccountIndexRouteImport } from './routes/(app)/(auth)/account/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRouteRoute = ApiChatRouteRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatRouteRoute = appChatRouteRouteImport.update({
  id: '/(app)/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const appChatIndexRoute = appChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appChatRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthSignUpIndexRoute = appauthSignUpIndexRouteImport.update({
  id: '/(app)/(auth)/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthSignInIndexRoute = appauthSignInIndexRouteImport.update({
  id: '/(app)/(auth)/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const appauthAccountIndexRoute = appauthAccountIndexRouteImport.update({
  id: '/(app)/(auth)/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof appChatRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chat/': typeof appChatIndexRoute
  '/account/': typeof appauthAccountIndexRoute
  '/sign-in/': typeof appauthSignInIndexRoute
  '/sign-up/': typeof appauthSignUpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/chat': typeof appChatIndexRoute
  '/account': typeof appauthAccountIndexRoute
  '/sign-in': typeof appauthSignInIndexRoute
  '/sign-up': typeof appauthSignUpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/chat': typeof appChatRouteRouteWithChildren
  '/api/chat': typeof ApiChatRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/chat/': typeof appChatIndexRoute
  '/(app)/(auth)/account/': typeof appauthAccountIndexRoute
  '/(app)/(auth)/sign-in/': typeof appauthSignInIndexRoute
  '/(app)/(auth)/sign-up/': typeof appauthSignUpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/api/chat'
    | '/api/auth/$'
    | '/chat/'
    | '/account/'
    | '/sign-in/'
    | '/sign-up/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/auth/$'
    | '/chat'
    | '/account'
    | '/sign-in'
    | '/sign-up'
  id:
    | '__root__'
    | '/'
    | '/(app)/chat'
    | '/api/chat'
    | '/api/auth/$'
    | '/(app)/chat/'
    | '/(app)/(auth)/account/'
    | '/(app)/(auth)/sign-in/'
    | '/(app)/(auth)/sign-up/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appChatRouteRoute: typeof appChatRouteRouteWithChildren
  ApiChatRouteRoute: typeof ApiChatRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  appauthAccountIndexRoute: typeof appauthAccountIndexRoute
  appauthSignInIndexRoute: typeof appauthSignInIndexRoute
  appauthSignUpIndexRoute: typeof appauthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat': {
      id: '/(app)/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof appChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/chat/': {
      id: '/(app)/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof appChatIndexRouteImport
      parentRoute: typeof appChatRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(auth)/sign-up/': {
      id: '/(app)/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof appauthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(auth)/sign-in/': {
      id: '/(app)/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof appauthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(auth)/account/': {
      id: '/(app)/(auth)/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof appauthAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appChatRouteRouteChildren {
  appChatIndexRoute: typeof appChatIndexRoute
}

const appChatRouteRouteChildren: appChatRouteRouteChildren = {
  appChatIndexRoute: appChatIndexRoute,
}

const appChatRouteRouteWithChildren = appChatRouteRoute._addFileChildren(
  appChatRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appChatRouteRoute: appChatRouteRouteWithChildren,
  ApiChatRouteRoute: ApiChatRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  appauthAccountIndexRoute: appauthAccountIndexRoute,
  appauthSignInIndexRoute: appauthSignInIndexRoute,
  appauthSignUpIndexRoute: appauthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
